contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - '@local /github/workspace/packages'
  packages:
    - alpine-baselayout-data
    - ca-certificates-bundle
    - git
    - my-helm-package@local

entrypoint:
  command: /bin/sh

archs:
  - amd64

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532