name: Build action

on: 
  push:
  schedule:
    - cron: '15 3 * * *'  # every day at 03:15 (just wanted to avoid midnight)

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo ::set-output name=date::$(date -u +%Y%m%d)
          echo ::set-output name=epoch::$(date -u +%s)
        shell: bash

      - uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        # with:
        #   platforms: x86_64,arm64
      
      - name: Install qemu-user
        run: sudo apt-get install -y qemu-user

      - uses: sigstore/cosign-installer@main
      
      - uses: chainguard-dev/actions/melange-build@main
        with:
          sign-with-temporary-key: true
          archs: x86_64,aarch64
          empty-workspace: true

      - uses: distroless/actions/apko-build@main
        id: apko
        with:
          tag: ghcr.io/${{ github.repository }}:latest
          keyring-append: /github/workspace/melange.rsa.pub
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}

      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v1.13.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - shell: bash
        run: |
          COSIGN_EXPERIMENTAL=true cosign sign ${{ steps.apko.outputs.digest }}
